---
:queues:
  - [products, 2]
  - [mailers, 1]
  - [rollbar, 1]
production:
  :concurrency: 10
  :schedule:
    sync:
      every: "5m"
      class: SyncWorker
staging:
  :concurrency: 10
development:
  :concurrency: 5
